server.port=${APP_PORT}

spring.datasource.username=${L_DB_USERNAME}
spring.datasource.password=${L_DB_PASSWORD}
spring.datasource.url=jdbc:postgresql://localhost:${L_DB_HOST_PORT}/${L_DB_NAME}

user.service.url=${LOCAL_USER_URL}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8082/api/auth/well-known/jwks.json